version: "3.6" #more than 3

services:
  #mongodb service mongo_db/mongo
  mongo_db:
    container_name: mongo-container #container name optional
    image: dockermern.azurecr.io/mongo:latest #contiane image from hub
    restart: always
    ports:
      - 2717:2717 #map port local-port:mongodb-container
    # volumes:
    #   - filesharemern:/data/db #mongodb:(this volum map to data/db) mongo db store data in ( dta/db)
#backend
  api:
    build: ./mernBackEnd #build image useing dockerfile
    image: dockermern.azurecr.io/mern-dockertask_api:latest
    container_name: container-name-backend-api
    ports:
      - 4000:4000 #localport:containerport
    environment:
        PORT: 4000
        # MONGODB_URI: mongodb://db_container:27017  #container/image name and it's port
        # DB_NAME: my_db #database name can be anything
        # NAME: TruelyMny  
    depends_on:
      - mongo_db #mongodb service name
#frontend
  # frontend:
  #   build: ./mernFrontEnd
  #   image: dockermern.azurecr.io/mern-dockertask_frontend:latest
  #   container_name: container-name-front-end
  #   ports:
  #     - '3000:3000' #localport:containerport
  #   depends_on:
  #     - mongo_db

# volumes:
#   data: 
#     driver: azure_file
#     driver_opts:
#       share_name: filesharemern #azure file shared
#       storage_account_name: storageaccountmern 
