version: "3.6" #more than 3

services:
  #mongodb service mongo_db/mongo
  mongo_db:
    container_name: mongo_container #container name optional
    image: mongo:latest #contiane image from hub
    restart: always
    ports:
      - 2717:27017 #map port local-port:mongodb-container
    volumes:
      - mongodb:/data/db #mongodb (this volum map to data/db) mongo db store data in ( dta/db)
#backend
  api:
    build: ./mernBackEnd #build image useing dockerfile
    ports:
      - 4000:3001 #localport:containerport
    environment:
        PORT: 3001
        # MONGODB_URI: mongodb://db_container:27017  #container/image name and it's port
        # DB_NAME: my_db #database name can be anything
        # NAME: TruelyMny  
    depends_on:
      - mongo_db #mongodb service name
#frontend
  frontend:
    build: ./mernFrontEnd
    ports:
      - 4001:3000 #localport:containerport
    depends_on:
      - mongo_db

volumes:
  mongodb: {}
